branches:
  only:
    - dev

language: node_js

sudo: false

node_js: stable

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - git config --global user.name "yukailis"
  - git config --global user.email " 18810456382@163.com"
  - git clone --branch master https://${GH_REF} dist

# script:
#   - npm test

after_success:
  - npm run build
  - cd dist
  - echo "test.ttftx.mobi" > CNAME
  - cp index.html 404.html
  - git add --all .
  - git commit --message "Automatically update from travis-ci"
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" master:master

# Note: you should set Environment Variables here or 'Settings' on travis-ci.org
env:
  global:
    - GH_REF: github.com/yukailis/web_vue_ttftx.git
